// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderProcessing.EmailWorker.Persistence;

#nullable disable

namespace OrderProcessing.EmailWorker.Migrations
{
    [DbContext(typeof(EmailWorkerDbContext))]
    [Migration("20260810183537_InitialEmailWorkerInbox")]
    partial class InitialEmailWorkerInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderProcessing.EmailWorker.Persistence.Entities.ProcessedMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("MessageId");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("ProcessedMessages", "email");
                });
#pragma warning restore 612, 618
        }
    }
}
